language: go
go:
  - 1.x
  - tip
# this allows forked projects to be buildt by travis before submitting pull reqs...
go_import_path: github.com/kelseyhightower/confd
env:
  - VAULT_ADDR='http://127.0.0.1:8200' CONSUL_VERSION=0.9.3 ETCD_VERSION=3.3.1 DYNAMODB_VERSION=2017-02-16 VAULT_VERSION=0.8.1 ZOOKEEPER_VERSION=3.4.10 RANCHER_VERSION=0.6.0
services:
  - redis
before_install:
  # install consul
  - wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul_${CONSUL_VERSION}_linux_amd64.zip
  - sudo mv consul /bin/
  - consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul -bind 127.0.0.1 &
  # install etcd
  - wget https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - tar xzf etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - sudo mv etcd-v${ETCD_VERSION}-linux-amd64/etcd /bin/
  - sudo mv etcd-v${ETCD_VERSION}-linux-amd64/etcdctl /bin/
  - unset ETCD_VERSION
  - etcd &
  # install DynamoDB
  - sudo pip install awscli
  - mkdir /tmp/dynamodb
  - wget -O - https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_${DYNAMODB_VERSION}.tar.gz | tar xz --directory /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
  # Install rancher metadata
  - wget https://github.com/rancher/rancher-metadata/releases/download/v${RANCHER_VERSION}/rancher-metadata.tar.gz
  - mkdir -p ./rancher-metadata
  - tar xzf rancher-metadata.tar.gz --strip-components=1 -C ./rancher-metadata
  - sudo mv ./rancher-metadata/bin/rancher-metadata /bin/
  # Install vault
  - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault_${VAULT_VERSION}_linux_amd64.zip
  - sudo mv vault /bin/
  - vault server -dev &
  # Install zookeeper
  - wget http://www.eu.apache.org/dist/zookeeper/zookeeper-${ZOOKEEPER_VERSION}/zookeeper-${ZOOKEEPER_VERSION}.tar.gz
  - tar xzf zookeeper-${ZOOKEEPER_VERSION}.tar.gz
  - mkdir /tmp/zookeeper && cp integration/zookeeper/zoo.cfg zookeeper-${ZOOKEEPER_VERSION}/conf/zoo.cfg
  - zookeeper-${ZOOKEEPER_VERSION}/bin/zkServer.sh start
  # Run AWS SSM mocking server
  - go run ./integration/ssm/main.go &
install:
  - make build
  - sudo make install
script:
  - make test
  - make integration
before_deploy:
- |
  for PLATFORM in windows linux darwin; do
    EXTENSION=""
    if [[ $PLATFORM = 'windows' ]]; then
      EXTENSION=".exe"
    fi
    export GOOS=$PLATFORM
    export GOARCH=amd64
    export CGO_ENABLED=0

    OUT_FILE="$GOPATH/bin/clconf-$PLATFORM$EXTENSION"
    echo "Creating $OUT_FILE ($TRAVIS_TAG)"
    go build -ldflags "-X github.com/kelseyhightower/confd/main.Version=$TRAVIS_TAG" -o $OUT_FILE
  done
  ls -lrt $GOPATH/bin
deploy:
  provider: releases
  api_key:
    secure: FgLzkb4joN3Wt7xfApBiPHFvpXp7LpxdJYjzkxMwLafvNmF5Gu1yVzaP5Tx/X0Jf31EZTvIVHX92xpNmtUFCbHXcTZ1NAuDioODsQ5zp4OaX3QhY+GrqK6jwGwmeS715PDm914dp7R785ojPGgxW+5CY+yFi2xmMaF4ChpgTOwG8dFS8RiK7kScRWvwfPW5E91XiHXCcZsLEDI7/rG6UF9K9QpLvSN2KmI59MaFDOMiPNQTo4gGD0/ProYWKQ5jUHCrNpMaj9q/GWsQwLnh9Xbxo/X7c5EDJTmVvqf61iWGSOgsWncPMkL05WQNRFLVL257/ORCHp+J6lJbZ23aNoN+kUfc+H66jG/yEeoUkJC7N4ezHTAW/JM8fNhoauau8OpnNfqHbHPsBn0XLCdSkOHSsb/jh1Wyk7rRP39fuQFNBUWiAvHPCVd4P0gybzCl237mQyH5QJvsFxwfAvD7GYugeybHeQb3+50/YPBa03+nZIL+b/UT52dvvBDa6Kz2lbOieiFH//U6wRU9hW8yZayUjj1WUBwyKJ/cBVMWGNYqMn8p3FAHNYOtwxQ4x+w/T/22ZBt4D0mqIprk9MxEV3I+InrJYH1JRuzKETmvz22/reuey0sYCSCD8f3gGbwoebUVSFxroTHdqHcBB2l4RAV39/MfbdGLDlskE+dF2xwE=
  file:
  - $GOPATH/bin/confd-linux
  - $GOPATH/bin/confd-darwin
  - $GOPATH/bin/confd-windows.exe
  skip_cleanup: true
  on:
    condition: $TRAVIS_GO_VERSION = "1.x" 
    tags: true